# syntax=docker/dockerfile:1
FROM python:3.10-alpine
RUN apk add --no-cache gcc musl-dev linux-headers libffi-dev g++
RUN pip install --upgrade pip
COPY reporter_root/requirements.txt /reporter/reporter_root/requirements.txt
RUN pip install -r /reporter/reporter_root/requirements.txt
COPY reporter_root /reporter/reporter_root
COPY config*.json /reporter/
WORKDIR /scraper
ENV PYTHONPATH "${PYTHONPATH}:/report"
CMD ["python3", "reporter_root/report.py"]
