# syntax=docker/dockerfile:1
FROM python:3.10
RUN apt-get install gcc libffi-dev g++
RUN pip install --upgrade pip
COPY scraper_root/requirements.txt /scraper/scraper_root/requirements.txt
RUN pip install -r /scraper/scraper_root/requirements.txt
COPY scraper_root /scraper/scraper_root
COPY config*.json /scraper/
COPY pyarmor.rkey /scraper/
WORKDIR /scraper
ENV PYTHONPATH "${PYTHONPATH}:/scraper"
CMD ["python3", "scraper_root/scraper.py"]